- errai-ui/src/main/java/org/jboss/errai/ui/shared/TemplateUtil.java
Adjust logging levels. In particular move logging of the templated document to finest() while others are moved from fine() to finer().
> Adjust logging levels.

- errai-data-binding/src/main/java/org/jboss/errai/databinding/client/BindableProxyAgent.java
- errai-data-binding/src/main/java/org/jboss/errai/databinding/client/api/Convert.java
- errai-data-binding/src/main/java/org/jboss/errai/databinding/client/api/Converter.java
- errai-data-binding/src/main/java/org/jboss/errai/ui/shared/api/annotations/Bound.java
- errai-data-binding/src/test/java/org/jboss/errai/databinding/client/TestModelTakesValueWidget.java
- errai-data-binding/src/test/java/org/jboss/errai/databinding/client/test/DataBindingIntegrationTest.java
Adds support for binding to ValueLabel<V> Widgets.
> ERRAI-831: Supporting binding Widgets that implement TakesValue<V>.

- errai-jpa/errai-jpa-client/src/main/java/org/jboss/errai/jpa/rebind/ErraiEntityManagerGenerator.java
>  #126 create own method for every entity type to prevent java function limit of 65536 bytes

- errai-bus/src/main/java/org/jboss/errai/bus/server/servlet/websocket/WebSocketNegotiationHandler.java
> ERRAI-873 websocket reconnect after network failure.

- errai-bom/pom.xml
- errai-cdi/jboss/pom.xml
Same changes were recently merged into master.
> [3.2] Remove dependency on jboss-as-dist

- errai-bom/pom.xml
- errai-security/errai-security-keycloak/pom.xml
- errai-ui/pom.xml
@mbarkley this is the changes we talked about yesterday. It was much easier than I anticipated :)
> Exclude commons-logging deps coming transitively + replace with jcl-over-slf4j where needed

- errai-bus-websocket/errai-bus-jsr356-websocket-weld/src/main/java/org/jboss/errai/bus/server/websocket/jsr356/weld/channel/CdiErraiWebSocketChannel.java
Proposed fix for https://issues.jboss.org/browse/ERRAI-915
> safely manage weld scopes deactivation for cdi websocket channel

- errai-bom/pom.xml
- pom.xml
* ip-bom import moved into errai-bom so that
all 3rd party dependencyManagement can happen
there
> Upgrade ip-bom to 7.0.0.CR1

- errai-common/src/main/java/org/jboss/errai/common/client/dom/DOMTokenList.java
JIRA: https://issues.jboss.org/browse/ERRAI-934
> [ERRAI-934] DOMTokenList is missing apis

- errai-jaxrs/README.md
- Fix broken links to old confluence documentation
- Fix / update errai community links
> Fix links in errai-jaxrs readme

- errai-bom/pom.xml
- errai-security/errai-security-server/pom.xml
- pom.xml
@mbarkley could you please take a look?
> 32x ip bom and javassist

- errai-bom/pom.xml
- errai-demos/errai-bus-demo-stock/pom.xml
- errai-demos/errai-bus-demo-stress-test/pom.xml
- errai-demos/errai-cdi-demo-mobile/pom.xml
- errai-demos/errai-cdi-demo-tagcloud/pom.xml
- errai-demos/errai-jaxrs-demo-crud/pom.xml
- errai-demos/errai-jpa-demo-basic/pom.xml
- errai-demos/errai-jpa-demo-grocery-list/pom.xml
- errai-demos/errai-jpa-demo-todo-list/pom.xml
- errai-demos/errai-security-demo/pom.xml
- errai-demos/errai-ui-demo-i18n/pom.xml
- pom.xml
JIRA: https://issues.jboss.org/browse/ERRAI-980
> [ERRAI-980] Upgrade to GWT 2.8.0-rc2

- errai-bom/pom.xml
- errai-demos/errai-bus-demo-stock/pom.xml
- errai-demos/errai-bus-demo-stress-test/pom.xml
- errai-demos/errai-cdi-demo-mobile/pom.xml
- errai-demos/errai-cdi-demo-tagcloud/pom.xml
- errai-demos/errai-jaxrs-demo-crud/pom.xml
- errai-demos/errai-jpa-demo-basic/pom.xml
- errai-demos/errai-jpa-demo-grocery-list/pom.xml
- errai-demos/errai-jpa-demo-todo-list/pom.xml
- errai-demos/errai-security-demo/pom.xml
- errai-demos/errai-ui-demo-i18n/pom.xml
- pom.xml
JIRA: https://issues.jboss.org/browse/ERRAI-985
> [ERRAI-985] Upgrade to GWT 2.8.0-rc3

- errai-marshalling/src/main/java/org/jboss/errai/marshalling/client/marshallers/ObjectMarshaller.java
See https://issues.jboss.org/browse/ERRAI-990
> ObjectMarshaller for null objects causes stack overflow

- errai-bom/pom.xml
- errai-bus/pom.xml
- errai-demos/errai-bus-demo-stress-test/pom.xml
- errai-demos/errai-jpa-demo-todo-list/pom.xml
- errai-demos/errai-security-demo/pom.xml
- errai-demos/errai-ui-demo-i18n/pom.xml
- errai-docs/src/main/asciidoc/reference.asciidoc
- errai-docs/src/main/docbook/en/reference.xml
- errai-forge-addon/src/main/java/org/jboss/errai/forge/constant/ArtifactVault.java
- errai-ioc-bus-support/pom.xml
- errai-jpa/errai-jpa-client/pom.xml
- errai-jpa/errai-jpa-client/src/main/java/org/jboss/errai/jpa/api/javax/persistence/ConstraintMode.java
- errai-jpa/errai-jpa-client/src/main/java/org/jboss/errai/jpa/api/javax/persistence/ForeignKey.java
- errai-jpa/errai-jpa-client/src/main/java/org/jboss/errai/jpa/api/javax/persistence/JoinColumn.java
- errai-jpa/errai-jpa-client/src/main/java/org/jboss/errai/jpa/rebind/TypedQueryFactoryGenerator.java
- errai-jpa/errai-jpa-client/src/test/java/org/jboss/errai/jpa/test/client/ErraiJpaTest.java
- errai-jpa/errai-jpa-datasync/pom.xml
- errai-jpa/errai-jpa-datasync/src/test/java/org/jboss/errai/jpa/sync/test/client/MockEntityManager.java
- errai-security/errai-security-client/pom.xml
- pom.xml
Please don't merge yet. All the IP BOM 7.0.0.CR5 PRs need to be merged together.
> IP BOM 7.0.0.CR5

- errai-navigation/src/main/java/org/jboss/errai/ui/nav/client/local/pushstate/HistoryImplPushState.java
Replace history token instead of push on navigation initialization.
This one fixes duplicated history entries after loading gwt host-page.
> ERRAI-1017: Replace history token on navigation initialization.

- errai-data-binding/src/main/java/org/jboss/errai/databinding/rebind/DataBindingUtil.java
- errai-data-binding/src/test/java/org/jboss/errai/databinding/client/scan/TestModelBindable.java
- errai-data-binding/src/test/java/org/jboss/errai/databinding/client/scan/TestModelWithoutBindableA.java
- errai-data-binding/src/test/java/org/jboss/errai/databinding/client/scan/TestModelWithoutBindableB.java
- errai-data-binding/src/test/java/org/jboss/errai/databinding/client/scan/TestModelWithoutBindableC.java
- errai-data-binding/src/test/java/org/jboss/errai/databinding/client/test/DataBindingIntegrationTest.java
- errai-data-binding/src/test/resources/ErraiApp.properties
```properties
errai.ui.bindableTypes=com.my.package1.* com.my.package2.* com.my.package3.BindableModel
```
> Add support for package scanning CONFIG_ERRAI_BINDABLE_TYPES

- errai-common/src/main/java/org/jboss/errai/common/client/dom/DOMUtil.java
- errai-common/src/test/java/org/jboss/errai/common/client/util/DOMUtilTest.java
See https://github.com/uberfire/uberfire/pull/617#pullrequestreview-19352724
> Add utilities to support HasCssName style enumerated CSS classes

- errai-marshalling/src/main/java/org/jboss/errai/marshalling/client/marshallers/OptionalMarshaller.java
- errai-marshalling/src/main/java/org/jboss/errai/marshalling/rebind/DefinitionsFactoryImpl.java
- errai-marshalling/src/test/java/org/jboss/errai/marshalling/tests/MarshallingAPITest.java
- errai-marshalling/src/test/java/org/jboss/errai/marshalling/tests/ServerMarshallingTest.java
I'm not sure if I ended up adding redundant tests though..
> ERRAI-1063: Add support for Optional fields in portable classes

- errai-config/src/main/java/org/jboss/errai/config/rebind/EnvUtil.java
- errai-data-binding/src/main/java/org/jboss/errai/databinding/rebind/DataBindingUtil.java
- errai-security/errai-security-client/src/main/java/org/jboss/errai/security/client/local/context/BasicUserCacheImpl.java
- errai-security/errai-security-client/src/main/java/org/jboss/errai/security/client/local/context/SecurityContextImpl.java
This catch is for wildcard serialization definitions (*).
If there is a better fix for these issues, I can update the PR.
Thanks
> Fix userCache proxy & avoid adding interfaces/abstracts as serializable types.

- errai-data-binding/src/main/java/org/jboss/errai/databinding/rebind/BindableProxyGenerator.java
Fixes https://issues.jboss.org/browse/ERRAI-1069
> ERRAI-1069: Data binding proxies performance and js size.

- errai-bom/pom.xml
- errai-bus/pom.xml
- errai-demos/errai-bus-demo-stress-test/pom.xml
- errai-demos/errai-cdi-demo-tagcloud/pom.xml
- errai-demos/errai-jpa-demo-todo-list/pom.xml
- errai-demos/errai-security-demo/pom.xml
- errai-demos/errai-ui-demo-i18n/pom.xml
needed by new cluster setup that @ederign is working on
> AF-569: upgrade netty version to align with activemq 

- errai-bom/pom.xml
- errai-bus-websocket/errai-bus-jsr356-websocket-weld/pom.xml
- errai-cdi/jboss/pom.xml
- pom.xml
Fixes version incompatibilities that lead to test failures in errai-bus-jsr356-websocket-weld.
> Upgrade ip bom

- errai-jaxrs/errai-jaxrs-client/pom.xml
- errai-jaxrs/errai-jaxrs-client/src/test/java/org/jboss/errai/enterprise/jaxrs/client/shared/entity/User.java
- errai-jaxrs/errai-jaxrs-client/src/test/java/org/jboss/errai/enterprise/jaxrs/server/JacksonTestServiceImpl.java
- errai-ui/pom.xml
- errai-ui/src/main/java/org/jboss/errai/ui/rebind/TranslationServiceGenerator.java
- errai-ui/src/test/java/org/jboss/errai/ui/test/i18n/client/I18nBundleTest.java
> Replace org.codehaus.jackson with com.fasterxml.jackson

- errai-bom/pom.xml
- errai-ui/src/main/java/org/jboss/errai/ui/rebind/TranslationServiceGenerator.java
It seems that I also modified some spaces into pom.xml, If those shouldn't be there tell me and I will revert them.
@mbarkley Can you review this please?
> [AF-549-elastaic]: upgraded jackson version to 2.8.8

- errai-bus-websocket/errai-bus-jsr356-websocket/src/main/java/org/jboss/errai/bus/server/websocket/jsr356/channel/DefaultErraiWebSocketChannel.java
- errai-bus/src/main/java/org/jboss/errai/bus/server/service/ErraiServiceImpl.java
- errai-bus/src/main/java/org/jboss/errai/bus/server/service/ErraiServiceProxy.java
- errai-bus/src/main/java/org/jboss/errai/bus/server/service/ErraiServiceSingleton.java
- errai-bus/src/main/java/org/jboss/errai/bus/server/service/MessageBusProxy.java
- errai-bus/src/main/java/org/jboss/errai/bus/server/service/RequestDispatcherProxy.java
- errai-bus/src/main/java/org/jboss/errai/bus/server/servlet/ServletBootstrapUtil.java
We need the service to reinitialize when the servlet refresh is invoked. Also the callbackList should be cleared perhaps this should be optional in the future.
> Fix issues with servlet reloading tools (like spring-boot-devtools).

- errai-ui/pom.xml
- errai-ui/src/main/java/org/jboss/errai/ui/rebind/chain/TemplateCatalog.java
this eliminates 10+ jar dependencies. Could not figure out how to bump up the jsoup version though?
> Removed Apache Stombol dependencies

- errai-data-binding/src/main/java/org/jboss/errai/databinding/rebind/BindableProxyGenerator.java
Also log a warning.
There were cases where I couldn't make complex classes bindable due to them having private properties.
Note that if there are use cases where protected property getters/setters need to be bound, it might be that we need to consider adding a check for protected since the `deepUnwrap` or `unwrap` access the getter/setters methods that throw an error.
> Gracefully ignore non-public properties in bindable proxies

- errai-data-binding/src/main/java/org/jboss/errai/databinding/rebind/BindableProxyGenerator.java
Address https://github.com/errai/errai/commit/816d25319a413ce37db21fe8b2b969f3e8d7d03a#commitcomment-27704555
Sorry for missing this when I implemented it, a lot of other streams of work at the time.
Thanks.
> Fix a bindable proxy generator regression

- RELEASE-PROCESS.md
Fixed the list ordering and other tiny changes.
> Slightly improved the Release Process steps

- errai-common/src/main/java/org/jboss/errai/common/client/dom/elemental2/Elemental2DomUtil.java
- errai-common/src/test/java/org/jboss/errai/common/client/dom/elemental2/Elemental2DomUtilTest.java
@tiagobento Would you mind to review?
Cherry picked from: https://github.com/errai/errai/pull/343
> Added method to convert an Elemental HTMLElement to Errai HTMLElement to deal with legacy Views

- errai-bus/src/main/java/org/jboss/errai/bus/client/api/builder/DefaultRemoteCallBuilder.java
- errai-bus/src/main/java/org/jboss/errai/bus/client/framework/AbstractRpcProxy.java
- errai-cdi/errai-cdi-shared/src/main/java/org/jboss/errai/enterprise/client/cdi/api/CDI.java
Related:
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/770
https://github.com/errai/errai/pull/350
https://github.com/kiegroup/appformer/pull/404
https://github.com/kiegroup/kie-wb-common/pull/1925
https://github.com/kiegroup/drools-wb/pull/878
https://github.com/kiegroup/jbpm-wb/pull/1162
https://github.com/kiegroup/optaplanner-wb/pull/288
https://github.com/kiegroup/kie-wb-distributions/pull/773
> AF-1226: Improve error handling displaying additional info to the GenericErrorPopup

- errai-bus/src/main/java/org/jboss/errai/bus/client/api/builder/DefaultRemoteCallBuilder.java
- errai-bus/src/main/java/org/jboss/errai/bus/client/framework/AbstractRpcProxy.java
- errai-cdi/errai-cdi-shared/src/main/java/org/jboss/errai/enterprise/client/cdi/api/CDI.java
This is already merged in 7.7.x. Cherry-picking to master.
Related:
https://github.com/errai/errai/pull/352
https://github.com/kiegroup/appformer/pull/412
https://github.com/kiegroup/kie-wb-common/pull/1951
https://github.com/kiegroup/drools-wb/pull/883
https://github.com/kiegroup/jbpm-wb/pull/1169
https://github.com/kiegroup/optaplanner-wb/pull/290
https://github.com/kiegroup/kie-wb-distributions/pull/776
> [master] AF-1226: Improve error handling displaying additional info to the GenericErrorPopup

- errai-bus/src/main/java/org/jboss/errai/bus/client/api/SessionExpiredException.java
- errai-bus/src/main/java/org/jboss/errai/bus/client/framework/ClientMessageBusImpl.java
- errai-bus/src/main/java/org/jboss/errai/bus/server/servlet/AbstractErraiServlet.java
Also fix sendDisconnectDueToSessionExpiry content type issue
> ERRAI-1112: Provide a way to determine SessionExpired on disconnects

- errai-bom/pom.xml
- errai-bus-websocket/errai-bus-jsr356-websocket-weld/pom.xml
- errai-cdi/errai-wildfly-dist/pom.xml
- errai-cdi/pom.xml
- errai-demos/errai-cdi-demo-mobile/pom.xml
- errai-demos/errai-cdi-demo-tagcloud/pom.xml
- errai-demos/errai-jaxrs-demo-crud/pom.xml
- errai-demos/errai-jpa-demo-basic/pom.xml
- errai-demos/errai-jpa-demo-grocery-list/pom.xml
- errai-demos/errai-jpa-demo-todo-list/pom.xml
- errai-demos/errai-jsinterop-demo/errai-jsinterop-demo-app/pom.xml
- errai-demos/errai-security-demo/pom.xml
- pom.xml
There is a concern related to SNAPSHOT version that will be solved in jboss-integration-platform-bom
@tiagobento could you review this please?
* https://github.com/jboss-integration/jboss-integration-platform-bom/pull/427
* https://github.com/errai/errai/pull/363
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/843
* https://github.com/kiegroup/appformer/pull/483
* https://github.com/kiegroup/kie-wb-common/pull/2147
* https://github.com/kiegroup/jbpm/pull/1336
* https://github.com/kiegroup/jbpm-wb/pull/1206
* https://github.com/kiegroup/drools/pull/2086
* https://github.com/kiegroup/droolsjbpm-integration/pull/1583
* https://github.com/kiegroup/kie-wb-distributions/pull/821 
* https://github.com/kiegroup/kie-docs/pull/1108
* https://github.com/kiegroup/optaplanner/pull/437
* …
> [AF-1555] Upgrade to Wildfly14

- errai-bom/pom.xml
- errai-bus/pom.xml
- errai-demos/errai-bus-demo-stress-test/pom.xml
- errai-demos/errai-jpa-demo-todo-list/pom.xml
- errai-demos/errai-security-demo/pom.xml
- errai-demos/errai-ui-demo-i18n/pom.xml
- errai-forge-addon/src/main/java/org/jboss/errai/forge/constant/ArtifactVault.java
- errai-ioc-bus-support/pom.xml
- errai-jpa/errai-jpa-client/pom.xml
- errai-jpa/errai-jpa-client/src/main/java/org/jboss/errai/jpa/rebind/ErraiEntityManagerGenerator.java
- errai-jpa/errai-jpa-client/src/main/java/org/jboss/errai/jpa/rebind/TypedQueryFactoryGenerator.java
- errai-jpa/errai-jpa-datasync/pom.xml
- errai-jpa/errai-jpa-datasync/src/test/java/org/jboss/errai/jpa/sync/test/client/MockEntityManager.java
- errai-security/errai-security-client/pom.xml
- pom.xml
ERRAI-1118: changes required for hibernate upgrade to 5.3.6.Final
(cherry picked from commit 47f3d4be363b9d2b45dd4f6131b2c2107a7b467b)
replaced org.hibernate.javax.persistence by javax.persistence
upgraded jboss-ip-bom
> hibernate and jboss-ip-bom upgrade

- errai-annotation-processors/pom.xml
- errai-bom/pom.xml
- errai-cdi/errai-wildfly-dist/pom.xml
- errai-cordova/pom.xml
- errai-demos/errai-cdi-demo-mobile/pom.xml
- errai-demos/errai-cdi-demo-tagcloud/pom.xml
- errai-demos/errai-jaxrs-demo-crud/pom.xml
- errai-demos/errai-jpa-demo-basic/pom.xml
- errai-demos/errai-jpa-demo-todo-list/pom.xml
- errai-demos/errai-security-demo/pom.xml
- errai-demos/errai-ui-demo-i18n/pom.xml
- pom.xml
change for https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1352
> Errai wf19 distro

- errai-bom/pom.xml
- errai-cdi/errai-wildfly-dist/pom.xml
A test PR for Wildfly 23.0.1.Final upgrade
> Wildfly 23.0.1.Final upgrade

- errai-bom/pom.xml
- errai-cdi/errai-wildfly-dist/pom.xml
- errai-demos/errai-cdi-demo-mobile/pom.xml
- errai-demos/errai-cdi-demo-tagcloud/pom.xml
- errai-demos/errai-jaxrs-demo-crud/pom.xml
- errai-demos/errai-jpa-demo-basic/pom.xml
Alig some versions according to what is available in WF23
> Aligning libraries version according to WF23

- errai-bom/pom.xml
- errai-bus-websocket/errai-bus-jsr356-websocket-weld/pom.xml
- errai-demos/errai-jsinterop-demo/errai-jsinterop-demo-app/pom.xml
- errai-demos/errai-jsinterop-demo/errai-jsinterop-demo-plugin/pom.xml
- errai-demos/errai-security-demo/pom.xml
https://github.com/errai/errai/pull/434
https://github.com/jesuino/droolsjbpm-build-bootstrap/pull/4
https://github.com/jesuino/kie-soup/pull/2
https://github.com/jesuino/drools/pull/2
https://github.com/jesuino/optaplanner/pull/2
https://github.com/jesuino/lienzo-core/pull/1
https://github.com/jesuino/lienzo-tests/pull/2
https://github.com/jesuino/appformer/pull/4
https://github.com/jesuino/jbpm/pull/4
https://github.com/jesuino/kie-jpmml-integration/pull/3
https://github.com/jesuino/droolsjbpm-integration/pull/5
https://github.com/jesuino/kie-wb-common/pull/5
https://github.com/jesuino/drools-wb/pull/3
https://github.com/jesuino/jbpm-work-items/pull/5
https://github.com/jesuino/jbpm-wb/pull/2
https://github.com/jesuino/kie-wb-distributions/pull/4 …
> Prepare to add banned dependencies on kie-parent
