errai/errai

- errai-cdi/errai-cdi-client/src/main/java/org/jboss/errai/enterprise/client/cdi/InstanceProvider.java
The generics removed in this PR are not supported in current Java 8 Gwt compilation.
If interested, the only other things I needed to do for Java 8 was to update javassist to the latest version.
> Remove java 8 incompatible generic signatures

- errai-codegen-gwt/src/main/java/org/jboss/errai/codegen/meta/impl/gwt/GWTParameterizedType.java
- errai-codegen-gwt/src/test/java/org/jboss/errai/codegen/gwt/test/GWTParameterizedTypeTest.java
- errai-codegen/src/test/java/org/jboss/errai/codegen/test/model/GenericArrayCollectionTestModel.java
GWTParameterizedType.getTypeParameters throw IllegalArgumentException
for generic array type parameter.
> Fixed generic array handling in GWTParameterizedType.getTypeParameters.

- errai-docs/src/main/asciidoc/reference.asciidoc
Mostly dropping space before special chars (`:;,.?)`) and after opening `(`.
> docs: More whitespace fixes

- errai-bom/pom.xml
- errai-cdi/jboss/pom.xml
* `jboss-as-dist` dependency does not seem to be used for testing and it should not be required for runtime either
* it is quite big (more than 100MiB) and it is being transitively dragged into other modules which use `errai-cdi-jboss`
> Remove dependency on jboss-as-dist

- errai-cdi/errai-cdi-client/src/main/java/org/jboss/errai/enterprise/client/cdi/events/BusReadyEvent.java
- errai-cdi/errai-cdi-server/pom.xml
@csadilek, @mbarkley please take a look. This is currently breaking all PR builds as we build Errai from sources.
> Add missing cdi-client for cdi-server tests

- errai-bom/pom.xml
To align with Guava version KIE Workbench is now using.
> Upgrade Guava from 19.0.0.jbossorg-1 to 19.0.0.jbossorg-2

- errai-cdi/jboss/src/main/java/org/jboss/errai/cdi/server/gwt/EmbeddedWildFlyLauncher.java
- errai-cdi/jboss/src/main/java/org/jboss/errai/cdi/server/gwt/util/JBossUtil.java
- errai-security/errai-security-server/src/main/java/org/jboss/errai/security/server/SecurityAnnotationExtension.java
Fixes warnings when starting OptaPlanner WB in Super Dev Mode
WARN  [org.jboss.weld.Event] WELD-000411: Observer method [BackedAnnotatedMethod] public org.jboss.errai.security.server.SecurityAnnotationExtension.addParameterLogger(@Observes ProcessAnnotatedType<Object>) receives events for all annotated types. Consider restricting events using @WithAnnotations or a generic type with bounds.
WARN: can't find jboss-cli.xml. Using default configuration values.
> PLANNER-579: Reduce WARN messages during startup

- errai-common/src/main/java/org/jboss/errai/common/client/util/Properties.java
- errai-common/src/test/java/org/jboss/errai/common/client/util/PropertiesTest.java
Bug example: 
Given a properties file:
key1=value1\:
key2=value2
The parser would just return one property with key "key1" and value "value1key2=value2" (ignoring the EOL).
> Fixing properties parser to read properties values ending with '\:' or '\=' correctly

- errai-cdi/jboss/src/main/java/org/jboss/errai/cdi/server/gwt/EmbeddedWildFlyLauncher.java
- errai-cdi/jboss/src/main/java/org/jboss/errai/cdi/server/gwt/util/JBossUtil.java
to the wildfly instance.
@csadilek @mbarkley can you guys let me know if we need a test for this. If so, can you point me out what test is checking the correct behavior for the normal App/Roles files? 
These changes are required to automatically create a users for the wildfly instance that is running in dev mode. The configuration files will be picked up (as the app/roles files) from the src/main/resources of the project starting GWT dev mode.
> adding support for copying mgmt users and group if provided 

- errai-cdi/errai-cdi-server/src/main/java/org/jboss/errai/cdi/server/scripts/HostPageScriptInjectorFilter.java
The default Jetty server run in super-dev-mode fails to start with an NPE prior to this change.
> Bypasses NPE when the hosting server has no CDI.

- errai-ui/pom.xml
```lesscss``` brings in dependency ```org.slf4j:slf4j-simple``` which causes upstream build errors (e.g. ```uberfire/uberfire-showcase/uberfire-client-webapp``` where Maven Enforcer Plugins fail the build should a duplicate class implementation be detected). It should be customary for end-user applications to specify logging implementations not transitive libraries.
> Exclude slf4j-simple from lesscss

- errai-ioc/src/main/java/org/jboss/errai/ioc/client/container/AbstractContext.java
- errai-ioc/src/main/java/org/jboss/errai/ioc/client/container/Proxy.java
- errai-ioc/src/main/java/org/jboss/errai/ioc/client/container/ProxyHelper.java
- errai-ioc/src/main/java/org/jboss/errai/ioc/client/container/ProxyHelperImpl.java
- errai-ioc/src/main/java/org/jboss/errai/ioc/rebind/ioc/bootstrapper/AbstractBodyGenerator.java
See https://issues.jboss.org/browse/ERRAI-1016
This PR simply renames the offending methods... I guess, ideally, Errai should use some form of internal method name representation to avoid/minimise conflicts in the future; but I'll leave that for @mbarkley to consider.
> ERRAI-1016: Duplicate method getContext() in generated Proxy error

- errai-codegen-gwt/src/main/java/org/jboss/errai/codegen/meta/impl/gwt/GWTClass.java
- errai-ioc/src/main/java/org/jboss/errai/ioc/rebind/ioc/bootstrapper/AbstractBodyGenerator.java
- errai-ioc/src/main/java/org/jboss/errai/ioc/rebind/ioc/bootstrapper/IOCProcessor.java
- errai-ioc/src/main/java/org/jboss/errai/ioc/rebind/ioc/graph/api/DependencyGraphBuilder.java
- errai-ioc/src/main/java/org/jboss/errai/ioc/rebind/ioc/graph/api/Injectable.java
- errai-ioc/src/main/java/org/jboss/errai/ioc/rebind/ioc/graph/impl/DefaultCustomFactoryInjectable.java
- errai-ioc/src/main/java/org/jboss/errai/ioc/rebind/ioc/graph/impl/DependencyGraphBuilderImpl.java
- errai-ioc/src/main/java/org/jboss/errai/ioc/rebind/ioc/graph/impl/ExtensionInjectable.java
- errai-ioc/src/main/java/org/jboss/errai/ioc/rebind/ioc/graph/impl/GraphUtil.java
- errai-ioc/src/main/java/org/jboss/errai/ioc/rebind/ioc/graph/impl/InjectableImpl.java
- errai-ioc/src/test/java/org/jboss/errai/ioc/tests/wiring/client/BasicIOCTest.java
- errai-ioc/src/test/java/org/jboss/errai/ioc/tests/wiring/client/res/QualForProducedTypeBean.java
- errai-ioc/src/test/java/org/jboss/errai/ioc/tests/wiring/client/res/QualForTypedBean.java
- errai-ioc/src/test/java/org/jboss/errai/ioc/tests/wiring/client/res/TypedBaseType.java
- errai-ioc/src/test/java/org/jboss/errai/ioc/tests/wiring/client/res/TypedProducer.java
- errai-ioc/src/test/java/org/jboss/errai/ioc/tests/wiring/client/res/TypedSuperInterface.java
- errai-ioc/src/test/java/org/jboss/errai/ioc/tests/wiring/client/res/TypedTargetInterface.java
- errai-ioc/src/test/java/org/jboss/errai/ioc/tests/wiring/client/res/TypedType.java
- errai-ioc/src/test/java/org/jboss/errai/ioc/unit/res/InjectsBeanByWrongTypes.java
- errai-ioc/src/test/java/org/jboss/errai/ioc/unit/res/InjectsInstanceFieldProducedBeanByWrongTypes.java
- errai-ioc/src/test/java/org/jboss/errai/ioc/unit/res/InjectsInstanceMethodProducedBeanByWrongTypes.java
- errai-ioc/src/test/java/org/jboss/errai/ioc/unit/res/InjectsStaticFieldProducedBeanByWrongTypes.java
- errai-ioc/src/test/java/org/jboss/errai/ioc/unit/res/InjectsStaticMethodProducedBeanByWrongTypes.java
- errai-ioc/src/test/java/org/jboss/errai/ioc/unit/test/IOCProcessorErrorTest.java
* Rework the mechanism for having injectables satisfy only injection
sites of the exact type of the injectable. Now each injectable supplies
a predicate that evaluates the path used to resolve itself for a given site.
The predicate can veto a path so that the injectable is not resolved
for that site.
* Use new path predicate mechanism to support @Typed. Beans with
@Typed have a predicate that only returns true if the injection
site is one of the types declared in the @Typed annotation.
> ERRAI-1018: Support for javax.enterprise.inject.Typed

- errai-marshalling/src/main/java/org/jboss/errai/marshalling/rebind/util/OutputDirectoryUtil.java
- No longer stop searching after first portable class was
found, but instead collect all matches (a portable class
could be found in a project that is not a webapp e.g.
errai-common when executed from errai root)
- Avoid writing ServerMarshallerFactory.class  files to
target dirs of projects which are no webapps
> ERRAI-1019: +Fix MarshallerModelStrategy (details below)

- errai-ioc/pom.xml
- errai-marshalling/pom.xml
We should generally be using the JBoss Spec Jars. These excluded
deps does not seem to be needed, so there is no replacement
for those at this point.
@mbarkley WDYT about this? The other option would be to make it `<scope>provided</scope>`, as I guess we could assume the CDI will be provided by the application server?
> Exclude el-api and interceptor-api from cdi-api

- errai-data-binding/src/main/java/org/jboss/errai/databinding/client/ListComponentProvider.java
- errai-data-binding/src/test/java/org/jboss/errai/databinding/client/TestModelWidget.java
- errai-data-binding/src/test/java/org/jboss/errai/databinding/client/test/ListBindingIntegrationTest.java
Changed the condition for the List Component destroyer initialization when its working with elements with Dependent scope
> Fixed List component destroyer initialization with Dependent scope

- errai-ui/pom.xml
See https://github.com/errai/errai/issues/258
> errai-data-binding is a non-optional dependency for errai-ui

- errai-cdi/jboss/src/main/java/org/jboss/errai/cdi/server/as/JBossServletContainerAdaptor.java
- errai-cdi/jboss/src/main/java/org/jboss/errai/cdi/server/gwt/EmbeddedWildFlyLauncher.java
- errai-cdi/jboss/src/main/java/org/jboss/errai/cdi/server/gwt/JBossLauncher.java
- errai-cdi/jboss/src/main/java/org/jboss/errai/cdi/server/gwt/util/JBossUtil.java
Replace
log.error(error message for /dev/null);
throw new UnableToCompleteException(no error message);
by
throw new IllegalStateException(error message);
See the jira for motivation:
https://issues.jboss.org/browse/ERRAI-1049
> ERRAI-1049 Do not eat the WildFly/JBoss launcher exception

- errai-common/src/main/java/org/jboss/errai/common/client/dom/BlobImpl.java
- errai-common/src/main/java/org/jboss/errai/common/client/dom/BlobPropertyBag.java
- errai-common/src/main/java/org/jboss/errai/common/client/dom/Window.java
Hey @mbarkley !
This commit includes a few `jsinterop` types and methods, I need those to achieve some features from [this ticket](https://issues.jboss.org/browse/JBPM-5861).
Thanks!
Roger
> JBPM-5861: Added JsInterop support for constructing Blob types and for the Window.atob function.

- errai-bus/src/main/java/org/jboss/errai/bus/client/ErraiBus.java
- errai-bus/src/main/java/org/jboss/errai/bus/client/api/builder/DefaultRemoteCallBuilder.java
- errai-bus/src/main/java/org/jboss/errai/bus/client/framework/ClientMessageBusImpl.java
- errai-cdi/errai-cdi-client/src/main/java/org/jboss/errai/enterprise/client/cdi/CDIClientBootstrap.java
- errai-common/src/main/java/org/jboss/errai/common/client/api/extension/InitVotes.java
- errai-common/src/main/java/org/jboss/errai/common/client/logging/LoggingHandlerConfigurator.java
- errai-ioc/src/main/java/org/jboss/errai/ioc/client/container/SyncBeanManagerImpl.java
- errai-marshalling/src/main/java/org/jboss/errai/marshalling/client/api/MarshallerFramework.java
- errai-security/errai-security-client/src/main/java/org/jboss/errai/security/client/local/context/SecurityContextImpl.java
This commit:
* Adds logging to audit startup to entrypoints, RPCs, bean manager
* Load RPC proxies before the bus initializes so that startup RPC calls
can be queued up and sent in a single payload
* Don't wait for bus to initialize to send CDI client associate message
(allows this to also be sent with initial bus payload)
* Don't delay InitVotes in SecurityContextImpl if a user has been injected
onto the host page
> AF-546: Reduce startup time of AppFormer apps and workbenches

- errai-common/src/main/java/org/jboss/errai/common/client/dom/DOMUtil.java
See https://issues.jboss.org/browse/JBPM-6207
```DOMUtils``` was calling ```Widget.onAttach()``` before it was attached to a parent. This leads to problems with 3rd party controls (in this specific case Bootstrap's "[Slider](https://github.com/seiyria/bootstrap-slider)" control) that require the Widget's parent element to be [set](https://github.com/seiyria/bootstrap-slider/blob/master/src/js/bootstrap-slider.js#L434) when ```onLoad()``` (called by ```onAttach()```) is called..
> JBPM-6207: [Forms Modeler] Slider based properties throw null exception

- errai-client-local-class-hider/pom.xml
- errai-demos/errai-security-demo/pom.xml
- errai-forge-addon/pom.xml
- errai-jboss-as-support/pom.xml
- Adding deployment skip configuration to `errai-demos/errai-security-demo` module.
- Adding `<distributionManagement />` configuration to `errai-forge-addon` module.
- Removing unnecessary `<distributionManagement />` configuration in `errai-client-local-class-hider` because it's inherited from `org.jboss:jboss-parent`. _(not necessary to fix Jenkins CI build)_
- Removing unnecessary dependency `junit:junit` in `errai-client-local-class-hider` because it's inherited from `errai-parent`. _(not necessary to fix Jenkins CI build)_
> Fix Jenkins CI build

- errai-common/src/main/java/org/jboss/errai/common/client/dom/TableCell.java
This was already made in https://github.com/errai/errai/pull/282 but have been mistakenly overriden by https://github.com/errai/errai/pull/286.
> Fix TableCell tag name mapping

- errai-navigation/src/main/java/org/jboss/errai/ui/nav/client/local/ContentDelegation.java
- errai-navigation/src/main/java/org/jboss/errai/ui/nav/client/local/DefaultContentDelegation.java
- errai-navigation/src/main/java/org/jboss/errai/ui/nav/client/local/Navigation.java
- errai-navigation/src/main/java/org/jboss/errai/ui/nav/client/local/api/DelegationControl.java
- errai-navigation/src/main/java/org/jboss/errai/ui/nav/client/local/api/NavigationControl.java
- errai-navigation/src/test/java/org/jboss/errai/ui/nav/client/local/testpages/BasePageForLifecycleTracing.java
This opens the door for custom content management using the ContentDelegation hooks.
It means we can create our our own multi-container layer app where certain content can be delegated to their own containers. It also allows for us to implement our own page transitions.
```java
navigation.setContentDelegation(new MyPageDelegation());
```
When the content is being set or cleared we have control over the process with this PR.
Let me know if there are any suggestions or nit picks and I can update the PR asap.
Thanks!
> Implementation of ContentDelegation interface

- errai-common/src/main/java/org/jboss/errai/common/client/dom/Window.java
Hey @mbarkley ,
As commented before, adding the `confirm` method in the Window object API because this needs to be back-ported to `7.3.x`/`4.0.x`. 
Thanks!
> AF-477: Support for Window's confirm method.

- errai-bus/src/main/java/org/jboss/errai/bus/server/io/websockets/WebSocketServerHandler.java
- errai-bus/src/main/java/org/jboss/errai/bus/server/service/ErraiConfigAttribs.java
Required to expand the default websocket frame size.
Pretty simple change, please let me know if there is a better implementation.
Thanks!
> Add errai.bus.web_socket_max_frame_size property

- errai-common/src/main/java/org/jboss/errai/common/client/api/annotations/ClassNames.java
- errai-ui/src/main/java/org/jboss/errai/ui/rebind/ioc/element/ElementInjectionBodyGenerator.java
- errai-ui/src/main/java/org/jboss/errai/ui/rebind/ioc/element/ElementProviderExtension.java
- errai-ui/src/test/java/org/jboss/errai/ui/test/integration/client/ErraiUICDIIntegrationTest.java
- errai-ui/src/test/java/org/jboss/errai/ui/test/integration/client/res/BeanWithElementInjectionSites.java
- errai-ui/src/test/java/org/jboss/errai/ui/test/integration/client/res/InputElementWithClassAndPropertyAnnotations.java
- errai-ui/src/test/java/org/jboss/errai/ui/test/integration/client/res/InputElementWithClassAnnotations.java
jira: https://issues.jboss.org/browse/ERRAI-1080
> [ERRAI-1080] Add @ClassName annotation support.

- errai-common/pom.xml
- errai-common/src/main/java/org/jboss/errai/common/client/dom/elemental2/Elemental2DomUtil.java
- errai-common/src/test/java/org/jboss/errai/common/client/dom/elemental2/Elemental2DomUtilTest.java
Regarding the `Elemental2DomUtil`, it's an Elemental2 approach for the deprecated `DOMUtil` (https://github.com/errai/errai/blob/master/errai-common/src/main/java/org/jboss/errai/common/client/dom/DOMUtil.java).
Regarding the `errai-internal-bom/pom.xml`, the `elemental2-dom` artifact is being added to avoid classes referenced via transitive dependencies. Since we're deprecating Errai elements in favor of Elementa2, we should make them available `errai-internal-bom/pom.xml`.
> Add Elemental2DomUtil (utility methods for interacting with the DOM)

- errai-tools/src/main/java/org/jboss/errai/tools/proxy/HttpClient.java
sun.misc.BASE64Encoder is no longer accessible in Java 9.
> Replace sun.misc.BASE64Encoder with java.util.Base64

- errai-bus/src/main/java/org/jboss/errai/bus/rebind/RpcProxyGenerator.java
The previous generation:
```java
} catch (Throwable throwable) {
if (errorCallback != null) {
errorCallback.error(null, throwable);
} else {
invokeDefaultErrorHandlers(throwable);
}
}
```
Becomes:
```java
} catch (Throwable throwable) {
if (errorCallback != null) {
if (errorCallback.error(null, throwable)) {
invokeDefaultErrorHandlers(throwable);
}
} else {
invokeDefaultErrorHandlers(throwable);
}
}
```
No longer ignoring the return type or `errorCallback.error`.
> Fixed issues where DefaultErrorHandlers wouldn't be invoked in RpcProxy's

- errai-bom/pom.xml
- errai-bus/src/test/java/org/jboss/errai/bus/TestCommon.gwt.xml
- errai-demos/errai-bus-demo-stock/pom.xml
- errai-demos/errai-bus-demo-stress-test/pom.xml
- errai-demos/errai-cdi-demo-mobile/pom.xml
- errai-demos/errai-cdi-demo-tagcloud/pom.xml
- errai-demos/errai-jaxrs-demo-crud/pom.xml
- errai-demos/errai-jpa-demo-basic/pom.xml
- errai-demos/errai-jpa-demo-grocery-list/pom.xml
- errai-demos/errai-jpa-demo-todo-list/pom.xml
- errai-demos/errai-security-demo/pom.xml
- errai-demos/errai-ui-demo-i18n/pom.xml
- errai-ioc-bus-support/src/test/java/org/jboss/errai/ioc/support/bus/tests/BusIOCSupportTests.gwt.xml
- errai-ioc-bus-support/src/test/java/org/jboss/errai/ioc/support/tests/factory/IOCFactoryTests.gwt.xml
- errai-security/errai-security-client/src/test/java/org/jboss/errai/security/SecurityInterceptorTest.gwt.xml
- errai-security/errai-security-client/src/test/java/org/jboss/errai/security/SecurityTest.gwt.xml
- errai-ui/pom.xml
- pom.xml
GWT 2.8.2 is the first release that should support bulding with Java 9
(it does not support Java 9 features; just the legacy classpath mode)
> Upgrade GWT to 2.8.2

- errai-bus/src/main/java/org/jboss/errai/bus/client/framework/ClientMessageBusImpl.java
- errai-bus/src/test/java/org/jboss/errai/bus/client/tests/ServiceAnnotationTests.java
- errai-cdi/errai-cdi-server/src/test/java/org/jboss/errai/cdi/event/client/test/CDIServiceAnnotationTests.java
This accounts for times where messages are ignored, rather than sink them, we should be throwing a NoSubscribersToDeliverTo exception.
Let me know if there is a more acceptable way to handle this.
> Fix issues where deferred messages error handling would be ignored.

- errai-cdi/errai-cdi-client/src/main/java/org/jboss/errai/enterprise/client/cdi/InstanceProvider.java
- errai-cdi/jboss/src/main/java/org/jboss/errai/cdi/server/gwt/EmbeddedWildFlyLauncher.java
- errai-demos/errai-jpa-demo-grocery-list/src/main/java/org/jboss/errai/demo/grocery/client/local/ItemForm.java
- errai-marshalling/src/main/java/org/jboss/errai/marshalling/rebind/api/impl/defaultjava/DefaultJavaMappingStrategy.java
- errai-navigation/src/main/java/org/jboss/errai/ui/nav/client/local/DefaultNavigationErrorHandler.java
- errai-navigation/src/main/java/org/jboss/errai/ui/nav/client/local/Navigation.java
- errai-navigation/src/main/java/org/jboss/errai/ui/nav/client/local/api/NavigationControl.java
- errai-navigation/src/main/java/org/jboss/errai/ui/nav/client/local/pushstate/HistoryImplPushState.java
- errai-navigation/src/main/java/org/jboss/errai/ui/nav/rebind/NavigationGraphGenerator.java
- errai-security/errai-security-client/src/main/java/org/jboss/errai/security/client/local/api/SecurityContext.java
- errai-security/errai-security-client/src/main/java/org/jboss/errai/security/client/local/callback/DefaultBusSecurityErrorCallback.java
- errai-security/errai-security-client/src/main/java/org/jboss/errai/security/client/local/callback/DefaultRestSecurityErrorCallback.java
- errai-security/errai-security-client/src/main/java/org/jboss/errai/security/client/local/context/SecurityContextImpl.java
- errai-security/errai-security-client/src/main/java/org/jboss/errai/security/client/local/handler/DefaultSecurityExceptionHandler.java
- errai-security/errai-security-client/src/main/java/org/jboss/errai/security/client/local/handler/SecurityExceptionHandler.java
- errai-security/errai-security-client/src/main/java/org/jboss/errai/security/client/local/interceptors/ClientSecurityRoleInterceptor.java
- errai-security/errai-security-client/src/test/java/org/jboss/errai/mocksafe/test/DefaultErrorCallbackTest.java
- errai-security/errai-security-keycloak/src/main/java/org/jboss/errai/security/keycloak/KeycloakAuthenticationService.java
- errai-ui/src/main/java/org/jboss/errai/ui/rebind/ioc/element/ElementInjectionBodyGenerator.java
- errai-ui/src/main/java/org/jboss/errai/ui/rebind/ioc/element/ElementProviderExtension.java
- errai-ui/src/main/java/org/jboss/errai/ui/shared/TemplateWidget.java
This fixes a security issue with ClientSecurityRoleInterceptor if an invalid user cache is found it simply proceeds the call, however we should check if there are required roles, if so, then we should not proceed, but instead throw an UnauthenticatedException. This lead to simply making the call before the user was validated and it would succeed.
Use a SecurityExceptionHandler to define SecurityException handling or stick with the default.
Example of using your own SecurityExceptionHandler:
```java
@Singleton
@Alternative
public class SecurityExceptionHandler extends DefaultSecurityExceptionHandler {
@Inject
public SecurityExceptionHandler(SecurityContext context) {
super(context);
}
@Override
public boolean handleException(Throwable caught) {
// We will only allow for redirection if we …
```
> Support custom security exception handling

- errai-data-binding/src/main/java/org/jboss/errai/databinding/rebind/DataBindingUtil.java
Sometimes interfaces are picked up in the bindable wildcard check. We can ignore them as we get an exception regarding no default constructor existing.
> Ignore bindable interfaces

- errai-marshalling/src/main/java/org/jboss/errai/marshalling/server/protocol/ErraiProtocolServer.java
- errai-marshalling/src/main/java/org/jboss/errai/marshalling/server/protocol/PayloadPreprocessor.java
https://issues.jboss.org/browse/ERRAI-1098
This allows us to preprocess the payload before it is encoded.
The most predominant use case we have at the moment is this example:
```java
public class HibernatePayloadPreprocessor implements PayloadPreprocessor {
@Override
public void process(Map<String, Object> payload) {
if(payload.containsKey("MethodReply")) {
payload.put("MethodReply", HibernateUtil.cleanFromProxies(payload.get("MethodReply")));
}
}
}
```
Then we would just need to call:
```java
ErraiProtocolServer.addPreprocessor(new HibernatePayloadPreprocessor());
```
This allows us to preprocess the payload before being sent to the encoder. We are able to avoid: `org.hibernate.LazyInitializationException: could not initialize proxy - no Session` exceptions.
Thanks!
> ERRAI-1098: Implement PayloadPreprocessor for server side payload processing

- errai-navigation/src/main/java/org/jboss/errai/ui/nav/client/local/Navigation.java
- errai-navigation/src/main/java/org/jboss/errai/ui/nav/client/local/PageUpdate.java
- errai-navigation/src/main/java/org/jboss/errai/ui/nav/client/local/spi/PageNode.java
- errai-navigation/src/main/java/org/jboss/errai/ui/nav/rebind/NavigationGraphGenerator.java
- errai-navigation/src/test/java/org/jboss/errai/ui/nav/client/local/PageLifecycleTest.java
- errai-navigation/src/test/java/org/jboss/errai/ui/nav/client/local/testpages/NonCompositePageWithLifecycleMethods.java
- errai-navigation/src/test/java/org/jboss/errai/ui/nav/client/local/testpages/PageWithLifecycleMethods.java
https://issues.jboss.org/browse/ERRAI-1099
This is something that we find very useful when it comes to retaining our pages workflow in the URL. With this we just call `updateState` with a new set of state data (or a modified version) and we retain the pages initial state.
Let me know if there are any unseen limitations here or if there would be a better way to manage something like this, but as far as I have tested it seems to be working very well.
Note that this isn't actually invoking a navigation, it is simply updating the URL for the next navigation attempt. If this isn't done the states will always match the currentPageToken's states when, navigating backwards for example and therefore the navigation process is ended prematurely.
This introduces the `@PageUpdate` lifecycle hook that …
> ERRAI-1099: Update current pages state without performing a full page navigation

- errai-navigation/src/main/java/org/jboss/errai/ui/nav/client/local/Navigation.java
This is a very simple patch that removes a single line of logging code.
```Navigation.setErrorHandler(....)``` allows the user to install custom error handler, which is supposed to handle navigation exception. Unfortunately, there is an extra line of logging code that emits a warning *before* the handler get a chance to process the exceptions. Further, ```DefaultNavigationErrorHandler``` already has plenty of logging already during the exception handling, so warning logs seems duplicate and clutters the browser JS console.
Please remove the single logging line with this pull request.
> Remove unneeded log.warning(...)

- errai-bus/src/main/java/org/jboss/errai/bus/client/ErraiBus.java
- errai-bus/src/main/java/org/jboss/errai/bus/client/api/ClientMessageBus.java
- errai-bus/src/main/java/org/jboss/errai/bus/client/api/messaging/MessageInterceptor.java
- errai-bus/src/main/java/org/jboss/errai/bus/client/framework/ClientMessageBusImpl.java
Allows us to do the following as an example:
```java
public class PingMessageInterceptor implements MessageInterceptor {
private long begin;
@Override
public void beforeCall(Message message) {
begin = new Date().getTime();
}
@Override
public void afterCall(Message message) {
// check the ping and perform tasks
}
}
```
```java
ErraiBus.get().addInterceptor(interceptor);
```
Now we can make checks on any remote call rather than just specific calls.
> ERRAI-1104: Ability to intercept any remote call from the ClientMessageBus

- errai-navigation/src/main/java/org/jboss/errai/ui/nav/client/local/api/NavigationControl.java
This valid for onHiding, when we want to cancel the hiding of a page.
> ERRAI-1108: Interrupt navigation without enforcing a redirect

- errai-bus/src/main/java/org/jboss/errai/bus/client/util/ErrorHelper.java
Due to the inverted condition, the throwable was actually ignored if it
wasn't null, which is the opposite of what was intended.
> Log throwable if it's not null

- errai-bom/pom.xml
- pom.xml
jboss-ip-bom 8.1.0.Final is identical to 8.1.0.CR2 - we had to do this as prod will work only with Final versions. In future there won't be anymore CRs for jboss-ip-bom - only Final versions.
> upgraded jboss-ip-bom to 8.1.0.Final

- .gitignore
- errai-codegen/pom.xml
- This commit keeps errai-codgen module aligned with the ecj version used by gwt-dev by doing a shade of the ecj classes contained in the gwt-dev.jar.
I this way the rest of the WB can use a different ecj version, etc, tipically configured in the droolsjbpm-build-boostrap file."
> Fix for ECJ - GWT conflict

- .gitignore
- errai-codegen/pom.xml
- This commit keeps errai-codgen module aligned with the ecj version used by gwt-dev by doing a shade of the ecj classes contained in the gwt-dev.jar.
I this way the rest of the WB can use a different ecj version, etc, tipically configured in the droolsjbpm-build-boostrap file."
(cherry picked from commit 207bb3059160314b7b63204da67516405ecba1ea)
> [4.3.x] Fix for ECJ - GWT conflict

- errai-common/pom.xml
- errai-ioc/pom.xml
- errai-navigation/pom.xml
- errai-security/errai-security-client/pom.xml
- errai-security/errai-security-server/pom.xml
@tiagobento same fix of the RHPAM-1743
> Fix XSD validation failure

- errai-marshalling/src/main/java/org/jboss/errai/marshalling/client/util/MarshallUtil.java
This PR fixes the failing test on `RpcHibernateTest` and enables new Hibernate proxies to be marshalled/unmarshalled like the old ones were.
> Fix Hibernate proxy objects marshalling

- errai-forge-addon/pom.xml
[![mitm_build](https://user-images.githubusercontent.com/1323708/59226671-90645200-8ba1-11e9-8ab3-39292bef99e9.jpeg)](https://medium.com/@jonathan.leitschuh/want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-1fc329d898fb?source=friends_link&sk=3c99970c55a899ad9ef41f126efcde0e)
- [Want to take over the Java ecosystem? All you need is a MITM!](https://medium.com/@jonathan.leitschuh/want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-1fc329d898fb?source=friends_link&sk=3c99970c55a899ad9ef41f126efcde0e)
- [Update: Want to take over the Java ecosystem? All you need is a MITM!](https://medium.com/bugbountywriteup/update-want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-d069d253fe23?source=friends_link&sk=8c8e52a7d57b98d0b7e541665688b454)
---
This is a security fix for …
> [SECURITY] Use HTTPS to resolve dependencies in Maven Build

- errai-jpa/errai-jpa-datasync/pom.xml
- errai-reflections/reflections/src/main/java/org/jboss/errai/reflections/util/ClasspathHelper.java
- errai-reflections/reflections/src/test/java/org/jboss/errai/reflections/VfsTest.java
- errai-validation/pom.xml
- errai-validation/src/main/java/org/jboss/errai/validation/rebind/GwtValidatorGenerator.java
This PR changes the way Errai finds `@Constraint`-annotated classes. Before, it was scanning the classpath, but on JDK11, the default classloader changed, making it not possible to do that anymore. 
This fix changes it to only scan for pre-configured constraints. Custom-defined constraints are still picked-up by scanning the GWT Generators classpath, so nothing changes on the upstream projects.
**Upgrade JDK 11 + GWT 2.9**
Feel free to comment and/or raise any concerns.
This PR continues the work done in 
- https://github.com/kiegroup/appformer/pull/1030
- https://github.com/kiegroup/appformer/pull/1039
Thanks guys for that!
**JIRA**:
[AF-1799](https://issues.redhat.com/browse/AF-1799)
**Parent Pull Request**:
- https://github.com/kiegroup/lienzo-core/pull/134
<details>
<summary>
How to …
> AF-1799: Upgrade JDK 11 + GWT 2.9

- RELEASE-PROCESS.md
@tiagobento Had to do some changes to RELEASE-PROCESS.md to not stumble in each release.
There are some things that have to be looked at:
1. https://github.com/errai/errai.github.com - is this still supported? There are still 8 years old commits?
2. Upload the docs: after doing scripts/upload_docs.sh {version} there was done scripts/upload_docs.sh latest --skip-mkdirs
3. and the error was: 
Uploading documentation...
mv: cannot stat 'Reference_Guide.pdf': No such file or directory
This is caused by https://github.com/errai/errai/blob/master/dist/scripts/upload_docs.sh#L34. The first time the doc is renamed and so not any more found the second time.
4. Is any one maintaining  the web for errai? It is somehow outdated.
> refactored RELEASE-PROCESS.md

- errai-annotation-processors/pom.xml
- errai-annotation-processors/src/test/java/org/jboss/errai/processor/AbstractProcessorTest.java
- errai-annotation-processors/src/test/java/org/jboss/errai/processor/EventHandlerAnnotationCheckerTest.java
- errai-bom/pom.xml
- errai-cdi/errai-cdi-client/src/test/java/org/jboss/errai/enterprise/client/cdi/AbstractErraiCDITest.java
- errai-codegen/src/test/java/org/jboss/errai/codegen/test/AnnotationEncoderTest.java
- errai-common/src/main/java/org/jboss/errai/common/client/types/TypeHandlerFactory.java
- errai-demos/errai-jpa-demo-basic/pom.xml
- errai-demos/errai-jpa-demo-grocery-list/pom.xml
- errai-demos/errai-jpa-demo-todo-list/pom.xml
- errai-demos/errai-jsinterop-demo/errai-jsinterop-demo-plugin/pom.xml
- errai-demos/errai-ui-demo-i18n/pom.xml
- errai-ioc/pom.xml
- errai-ioc/src/main/java/org/jboss/errai/ioc/rebind/ioc/bootstrapper/TypeFactoryBodyGenerator.java
- errai-jpa/errai-jpa-client/pom.xml
- errai-jpa/errai-jpa-datasync/pom.xml
- errai-reflections/reflections/src/main/java/org/jboss/errai/reflections/util/ClasspathHelper.java
- errai-reflections/reflections/src/test/java/org/jboss/errai/reflections/VfsTest.java
- errai-tools/src/main/java/org/jboss/errai/tools/proxy/HttpClient.java
- errai-validation/pom.xml
- pom.xml
the latest PR CI with jdk11 which is a Jenkins CI default runtime jobs failed on 
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0-jboss-1:compile (default-compile) on project errai-ioc: Compilation failure: Compilation failure: 
[ERROR] /home/jenkins/workspace/KIE/main/pullrequest/errai-main.pr/errai/errai-ioc/src/main/java/org/jboss/errai/ioc/rebind/ioc/bootstrapper/IOCProcessor.java:[50,24] cannot find symbol
[ERROR]   symbol:   class PostConstruct
[ERROR]   location: package javax.annotation
[ERROR] /home/jenkins/workspace/KIE/main/pullrequest/errai-main.pr/errai/errai-ioc/src/main/java/org/jboss/errai/ioc/rebind/ioc/bootstrapper/TypeFactoryBodyGenerator.java:[43,24] cannot find symbol
[ERROR]   symbol:   class PostConstruct
[ERROR]   location: …
```
> Fixing main branch to compile and pass all tests with JDK11
